# Translation dictionaries for backend services

TRANSLATIONS = {
    'en': {
        # Soil Health Analysis
        'soil_nitrogen_low': 'Soil nitrogen is low',
        'soil_nitrogen_high': 'Soil nitrogen is high',
        'soil_nitrogen_adequate': 'Soil nitrogen levels are adequate',
        'add_nitrogen_fertilizers': 'Add nitrogen-rich fertilizers like urea or compost',
        'avoid_nitrogen_heavy': 'Avoid nitrogen-heavy fertilizers, focus on balanced NPK',
        
        'soil_potassium_low': 'Soil potassium is low',
        'soil_potassium_high': 'Soil potassium is high',
        'soil_potassium_adequate': 'Soil potassium levels are adequate',
        'add_potassium_sulfate': 'Add potassium sulfate or wood ash to improve soil K levels',
        'reduce_potassium_inputs': 'Reduce potassium inputs, focus on nitrogen and phosphorus',
        
        'soil_phosphorus_low': 'Soil phosphorus is low',
        'soil_phosphorus_high': 'Soil phosphorus is high',
        'soil_phosphorus_adequate': 'Soil phosphorus levels are adequate',
        'add_bone_meal': 'Add bone meal, rock phosphate, or DAP fertilizer',
        'avoid_phosphorus_heavy': 'Avoid phosphorus-heavy fertilizers, focus on nitrogen and potassium',
        
        'temperature_low': 'Temperature is low for most crops',
        'temperature_high': 'Temperature is high',
        'temperature_optimal': 'Temperature is optimal for crop growth',
        'cold_tolerant_crops': 'Consider cold-tolerant crops or greenhouse cultivation',
        'adequate_irrigation': 'Ensure adequate irrigation and consider heat-tolerant varieties',
        
        'humidity_low': 'Low humidity detected',
        'humidity_high': 'High humidity detected',
        'humidity_suitable': 'Humidity levels are suitable',
        'increase_irrigation': 'Increase irrigation frequency and consider mulching',
        'good_drainage': 'Ensure good drainage and air circulation to prevent diseases',
        
        'moisture_low': 'Soil moisture is low',
        'moisture_high': 'Soil moisture is high',
        'moisture_adequate': 'Soil moisture levels are adequate',
        'increase_irrigation_organic': 'Increase irrigation and add organic matter to improve water retention',
        'improve_drainage': 'Improve drainage and avoid overwatering',
        
        # Soil type recommendations
        'soil_type_clayey': 'Clay soil retains water well but may need organic matter for better drainage',
        'soil_type_loamy': 'Loamy soil is ideal for most crops with good drainage and water retention',
        'soil_type_sandy': 'Sandy soil drains quickly, add organic matter and increase irrigation frequency',
        'soil_type_red': 'Red soil is typically well-drained, ensure adequate organic matter',
        'soil_type_black': 'Black soil is fertile but may need pH adjustment for optimal crop growth',
        
        # Status
        'excellent': 'Excellent',
        'good': 'Good',
        'fair': 'Fair',
        'poor': 'Poor',
        
        # Report sections
        'report_title': 'Krushak Fertilizer Recommendation Report',
        'generated_on': 'Generated on:',
        'input_parameters': 'Input Parameters',
        'weather_information': 'Weather Information',
        'fertilizer_predictions': 'Fertilizer Predictions',
        'soil_health_analysis': 'Soil Health Analysis',
        'overall_health_score': 'Overall Health Score',
        'status': 'Status',
        'key_insights': 'Key Insights',
        'recommendations': 'Recommendations',
        'report_footer': 'Generated by Krushak Fertilizer Recommendation System',
        'model_confidence_comparison': 'Model Confidence Comparison',
        'confidence': 'Confidence',
        'models': 'Models',
        'report_contents': 'Report Contents',
        'input_parameters_desc': 'User input data',
        'predictions_desc': 'ML model results',
        'soil_health_desc': 'Analysis and recommendations',
        'weather_data_desc': 'Current weather conditions',
        'summary_desc': 'This overview'
    },
    
    'hi': {
        # Soil Health Analysis
        'soil_nitrogen_low': 'मिट्टी में नाइट्रोजन कम है',
        'soil_nitrogen_high': 'मिट्टी में नाइट्रोजन अधिक है',
        'soil_nitrogen_adequate': 'मिट्टी में नाइट्रोजन का स्तर पर्याप्त है',
        'add_nitrogen_fertilizers': 'यूरिया या कम्पोस्ट जैसे नाइट्रोजन युक्त उर्वरक डालें',
        'avoid_nitrogen_heavy': 'नाइट्रोजन भारी उर्वरकों से बचें, संतुलित NPK पर ध्यान दें',
        
        'soil_potassium_low': 'मिट्टी में पोटेशियम कम है',
        'soil_potassium_high': 'मिट्टी में पोटेशियम अधिक है',
        'soil_potassium_adequate': 'मिट्टी में पोटेशियम का स्तर पर्याप्त है',
        'add_potassium_sulfate': 'मिट्टी के K स्तर में सुधार के लिए पोटेशियम सल्फेट या लकड़ी की राख डालें',
        'reduce_potassium_inputs': 'पोटेशियम इनपुट कम करें, नाइट्रोजन और फॉस्फोरस पर ध्यान दें',
        
        'soil_phosphorus_low': 'मिट्टी में फॉस्फोरस कम है',
        'soil_phosphorus_high': 'मिट्टी में फॉस्फोरस अधिक है',
        'soil_phosphorus_adequate': 'मिट्टी में फॉस्फोरस का स्तर पर्याप्त है',
        'add_bone_meal': 'बोन मील, रॉक फॉस्फेट, या DAP उर्वरक डालें',
        'avoid_phosphorus_heavy': 'फॉस्फोरस भारी उर्वरकों से बचें, नाइट्रोजन और पोटेशियम पर ध्यान दें',
        
        'temperature_low': 'अधिकांश फसलों के लिए तापमान कम है',
        'temperature_high': 'तापमान अधिक है',
        'temperature_optimal': 'फसल वृद्धि के लिए तापमान अनुकूल है',
        'cold_tolerant_crops': 'ठंड सहनशील फसलों या ग्रीनहाउस खेती पर विचार करें',
        'adequate_irrigation': 'पर्याप्त सिंचाई सुनिश्चित करें और गर्मी सहनशील किस्मों पर विचार करें',
        
        'humidity_low': 'कम आर्द्रता का पता चला',
        'humidity_high': 'उच्च आर्द्रता का पता चला',
        'humidity_suitable': 'आर्द्रता का स्तर उपयुक्त है',
        'increase_irrigation': 'सिंचाई की आवृत्ति बढ़ाएं और मल्चिंग पर विचार करें',
        'good_drainage': 'रोगों को रोकने के लिए अच्छे जल निकासी और वायु परिसंचरण सुनिश्चित करें',
        
        'moisture_low': 'मिट्टी की नमी कम है',
        'moisture_high': 'मिट्टी की नमी अधिक है',
        'moisture_adequate': 'मिट्टी की नमी का स्तर पर्याप्त है',
        'increase_irrigation_organic': 'सिंचाई बढ़ाएं और जल प्रतिधारण में सुधार के लिए जैविक पदार्थ डालें',
        'improve_drainage': 'जल निकासी में सुधार करें और अधिक सिंचाई से बचें',
        
        # Soil type recommendations
        'soil_type_clayey': 'चिकनी मिट्टी पानी को अच्छी तरह रोकती है लेकिन बेहतर जल निकासी के लिए जैविक पदार्थ की आवश्यकता हो सकती है',
        'soil_type_loamy': 'दोमट मिट्टी अधिकांश फसलों के लिए आदर्श है जिसमें अच्छी जल निकासी और जल प्रतिधारण होता है',
        'soil_type_sandy': 'बलुई मिट्टी तेजी से निकल जाती है, जैविक पदार्थ डालें और सिंचाई की आवृत्ति बढ़ाएं',
        'soil_type_red': 'लाल मिट्टी आमतौर पर अच्छी तरह से निकलती है, पर्याप्त जैविक पदार्थ सुनिश्चित करें',
        'soil_type_black': 'काली मिट्टी उपजाऊ है लेकिन इष्टतम फसल वृद्धि के लिए pH समायोजन की आवश्यकता हो सकती है',
        
        # Status
        'excellent': 'उत्कृष्ट',
        'good': 'अच्छा',
        'fair': 'ठीक',
        'poor': 'खराब',
        
        # Report sections
        'report_title': 'कृषक उर्वरक सिफारिश रिपोर्ट',
        'generated_on': 'जेनरेट किया गया:',
        'input_parameters': 'इनपुट पैरामीटर',
        'weather_information': 'मौसम की जानकारी',
        'fertilizer_predictions': 'उर्वरक भविष्यवाणी',
        'soil_health_analysis': 'मिट्टी स्वास्थ्य विश्लेषण',
        'overall_health_score': 'समग्र स्वास्थ्य स्कोर',
        'status': 'स्थिति',
        'key_insights': 'मुख्य अंतर्दृष्टि',
        'recommendations': 'सिफारिशें',
        'report_footer': 'कृषक उर्वरक सिफारिश प्रणाली द्वारा जेनरेट',
        'model_confidence_comparison': 'मॉडल आत्मविश्वास तुलना',
        'confidence': 'आत्मविश्वास',
        'models': 'मॉडल',
        'report_contents': 'रिपोर्ट सामग्री',
        'input_parameters_desc': 'उपयोगकर्ता इनपुट डेटा',
        'predictions_desc': 'ML मॉडल परिणाम',
        'soil_health_desc': 'विश्लेषण और सिफारिशें',
        'weather_data_desc': 'वर्तमान मौसम की स्थिति',
        'summary_desc': 'यह अवलोकन'
    },
    
    'mr': {
        # Soil Health Analysis
        'soil_nitrogen_low': 'मातीत नायट्रोजन कम आहे',
        'soil_nitrogen_high': 'मातीत नायट्रोजन जास्त आहे',
        'soil_nitrogen_adequate': 'मातीत नायट्रोजनची पातळी पुरेशी आहे',
        'add_nitrogen_fertilizers': 'युरिया किंवा कंपोस्ट सारखे नायट्रोजनयुक्त खते घाला',
        'avoid_nitrogen_heavy': 'नायट्रोजन भारी खतांपासून दूर रहा, संतुलित NPK वर लक्ष द्या',
        
        'soil_potassium_low': 'मातीत पोटॅशियम कमी आहे',
        'soil_potassium_high': 'मातीत पोटॅशियम जास्त आहे',
        'soil_potassium_adequate': 'मातीत पोटॅशियमची पातळी पुरेशी आहे',
        'add_potassium_sulfate': 'मातीच्या K पातळीत सुधारण्यासाठी पोटॅशियम सल्फेट किंवा लाकडाची राख घाला',
        'reduce_potassium_inputs': 'पोटॅशियम इनपुट कमी करा, नायट्रोजन आणि फॉस्फरस वर लक्ष द्या',
        
        'soil_phosphorus_low': 'मातीत फॉस्फरस कमी आहे',
        'soil_phosphorus_high': 'मातीत फॉस्फरस जास्त आहे',
        'soil_phosphorus_adequate': 'मातीत फॉस्फरसची पातळी पुरेशी आहे',
        'add_bone_meal': 'बोन मील, रॉक फॉस्फेट, किंवा DAP खत घाला',
        'avoid_phosphorus_heavy': 'फॉस्फरस भारी खतांपासून दूर रहा, नायट्रोजन आणि पोटॅशियम वर लक्ष द्या',
        
        'temperature_low': 'बहुतेक पिकांसाठी तापमान कमी आहे',
        'temperature_high': 'तापमान जास्त आहे',
        'temperature_optimal': 'पिकाच्या वाढीसाठी तापमान अनुकूल आहे',
        'cold_tolerant_crops': 'थंड सहनशील पिके किंवा ग्रीनहाउस लागवड विचारात घ्या',
        'adequate_irrigation': 'पुरेशी सिंचन सुनिश्चित करा आणि उष्णता सहनशील जाती विचारात घ्या',
        
        'humidity_low': 'कमी आर्द्रता आढळली',
        'humidity_high': 'उच्च आर्द्रता आढळली',
        'humidity_suitable': 'आर्द्रतेची पातळी योग्य आहे',
        'increase_irrigation': 'सिंचनाची वारंवारता वाढवा आणि मल्चिंग विचारात घ्या',
        'good_drainage': 'रोगांना प्रतिबंध करण्यासाठी चांगली जलनिकासी आणि हवेचे परिसंचरण सुनिश्चित करा',
        
        'moisture_low': 'मातीची ओलावा कमी आहे',
        'moisture_high': 'मातीची ओलावा जास्त आहे',
        'moisture_adequate': 'मातीच्या ओलावाची पातळी पुरेशी आहे',
        'increase_irrigation_organic': 'सिंचन वाढवा आणि पाणी धारणा सुधारण्यासाठी सेंद्रिय पदार्थ घाला',
        'improve_drainage': 'जलनिकासी सुधारा आणि जास्त सिंचन टाळा',
        
        # Soil type recommendations
        'soil_type_clayey': 'चिकणमाती पाणी चांगले धरते पण चांगल्या जलनिकासीसाठी सेंद्रिय पदार्थाची गरज असू शकते',
        'soil_type_loamy': 'दोमट माती बहुतेक पिकांसाठी आदर्श आहे ज्यात चांगली जलनिकासी आणि पाणी धारणा असते',
        'soil_type_sandy': 'वाळूची माती लवकर निघते, सेंद्रिय पदार्थ घाला आणि सिंचनाची वारंवारता वाढवा',
        'soil_type_red': 'लाल माती सामान्यतः चांगली निघते, पुरेशा सेंद्रिय पदार्थाची खात्री करा',
        'soil_type_black': 'काळी माती सुपीक आहे पण इष्टतम पिक वाढीसाठी pH समायोजनाची गरज असू शकते',
        
        # Status
        'excellent': 'उत्कृष्ट',
        'good': 'चांगले',
        'fair': 'बरं',
        'poor': 'वाईट',
        
        # Report sections
        'report_title': 'कृषक खत सूचना अहवाल',
        'generated_on': 'जेनरेट केले:',
        'input_parameters': 'इनपुट पॅरामीटर्स',
        'weather_information': 'हवामान माहिती',
        'fertilizer_predictions': 'खत अंदाज',
        'soil_health_analysis': 'माती आरोग्य विश्लेषण',
        'overall_health_score': 'एकूण आरोग्य स्कोर',
        'status': 'स्थिती',
        'key_insights': 'मुख्य अंतर्दृष्टी',
        'recommendations': 'सूचना',
        'report_footer': 'कृषक खत सूचना प्रणालीद्वारे जेनरेट',
        'model_confidence_comparison': 'मॉडेल आत्मविश्वास तुलना',
        'confidence': 'आत्मविश्वास',
        'models': 'मॉडेल्स',
        'report_contents': 'अहवाल सामग्री',
        'input_parameters_desc': 'वापरकर्ता इनपुट डेटा',
        'predictions_desc': 'ML मॉडेल परिणाम',
        'soil_health_desc': 'विश्लेषण आणि सूचना',
        'weather_data_desc': 'सध्याच्या हवामानाच्या परिस्थिती',
        'summary_desc': 'हे आढावे'
    },
    
    'te': {
        # Soil Health Analysis
        'soil_nitrogen_low': 'నేలలో నత్రజని తక్కువ',
        'soil_nitrogen_high': 'నేలలో నత్రజని ఎక్కువ',
        'soil_nitrogen_adequate': 'నేలలో నత్రజని స్థాయి తగినంత',
        'add_nitrogen_fertilizers': 'యూరియా లేదా కంపోస్ట్ వంటి నత్రజని ఎరువులు వేయండి',
        'avoid_nitrogen_heavy': 'నత్రజని భారీ ఎరువులను నివారించండి, సమతుల్య NPKపై దృష్టి పెట్టండి',
        
        'soil_potassium_low': 'నేలలో పొటాషియం తక్కువ',
        'soil_potassium_high': 'నేలలో పొటాషియం ఎక్కువ',
        'soil_potassium_adequate': 'నేలలో పొటాషియం స్థాయి తగినంత',
        'add_potassium_sulfate': 'నేల K స్థాయిని మెరుగుపరచడానికి పొటాషియం సల్ఫేట్ లేదా చెక్క బూడిద వేయండి',
        'reduce_potassium_inputs': 'పొటాషియం ఇన్పుట్లను తగ్గించండి, నత్రజని మరియు భాస్వరంపై దృష్టి పెట్టండి',
        
        'soil_phosphorus_low': 'నేలలో భాస్వరం తక్కువ',
        'soil_phosphorus_high': 'నేలలో భాస్వరం ఎక్కువ',
        'soil_phosphorus_adequate': 'నేలలో భాస్వరం స్థాయి తగినంత',
        'add_bone_meal': 'ఎముక పొడి, రాక్ ఫాస్ఫేట్, లేదా DAP ఎరువు వేయండి',
        'avoid_phosphorus_heavy': 'భాస్వరం భారీ ఎరువులను నివారించండి, నత్రజని మరియు పొటాషియంపై దృష్టి పెట్టండి',
        
        'temperature_low': 'చాలా పంటలకు ఉష్ణోగ్రత తక్కువ',
        'temperature_high': 'ఉష్ణోగ్రత ఎక్కువ',
        'temperature_optimal': 'పంట వృద్ధికి ఉష్ణోగ్రత అనుకూలమైనది',
        'cold_tolerant_crops': 'చలి సహనశీల పంటలు లేదా గ్రీన్‌హౌస్ సాగుపై ఆలోచించండి',
        'adequate_irrigation': 'తగిన సాగునీటిని నిర్ధారించండి మరియు వేడి సహనశీల వంటలపై ఆలోచించండి',
        
        'humidity_low': 'తక్కువ తేమ గుర్తించబడింది',
        'humidity_high': 'ఎక్కువ తేమ గుర్తించబడింది',
        'humidity_suitable': 'తేమ స్థాయి తగినది',
        'increase_irrigation': 'సాగునీటి పౌనఃపున్యాన్ని పెంచండి మరియు మల్చింగ్‌పై ఆలోచించండి',
        'good_drainage': 'వ్యాధులను నివారించడానికి మంచి జలనిక్షేపణ మరియు గాలి ప్రసరణను నిర్ధారించండి',
        
        'moisture_low': 'నేల తేమ తక్కువ',
        'moisture_high': 'నేల తేమ ఎక్కువ',
        'moisture_adequate': 'నేల తేమ స్థాయి తగినంత',
        'increase_irrigation_organic': 'సాగునీటిని పెంచండి మరియు నీటి నిలుపుదలను మెరుగుపరచడానికి సేంద్రీయ పదార్థాన్ని జోడించండి',
        'improve_drainage': 'జలనిక్షేపణను మెరుగుపరచండి మరియు అధిక సాగునీటిని నివారించండి',
        
        # Soil type recommendations
        'soil_type_clayey': 'మట్టి నేల నీటిని బాగా నిలుపుతుంది కానీ మంచి జలనిక్షేపణకు సేంద్రీయ పదార్థం అవసరం కావచ్చు',
        'soil_type_loamy': 'మట్టి నేల చాలా పంటలకు ఆదర్శమైనది, మంచి జలనిక్షేపణ మరియు నీటి నిలుపుదలతో',
        'soil_type_sandy': 'ఇసుక నేల త్వరగా వదిలివేస్తుంది, సేంద్రీయ పదార్థాన్ని జోడించండి మరియు సాగునీటి పౌనఃపున్యాన్ని పెంచండి',
        'soil_type_red': 'ఎరుపు నేల సాధారణంగా బాగా వదిలివేస్తుంది, తగిన సేంద్రీయ పదార్థాన్ని నిర్ధారించండి',
        'soil_type_black': 'నల్ల నేల సారవంతమైనది కానీ సరైన పంట వృద్ధికి pH సర్దుబాటు అవసరం కావచ్చు',
        
        # Status
        'excellent': 'అద్భుతమైన',
        'good': 'మంచిది',
        'fair': 'సరసమైన',
        'poor': 'చెడ్డది',
        
        # Report sections
        'report_title': 'కృషక్ ఎరువు సిఫార్సు నివేదిక',
        'generated_on': 'జనరేట్ చేయబడింది:',
        'input_parameters': 'ఇన్‌పుట్ పారామీటర్లు',
        'weather_information': 'వాతావరణ సమాచారం',
        'fertilizer_predictions': 'ఎరువు అంచనాలు',
        'soil_health_analysis': 'నేల ఆరోగ్య విశ్లేషణ',
        'overall_health_score': 'మొత్తం ఆరోగ్య స్కోర్',
        'status': 'స్థితి',
        'key_insights': 'ముఖ్య అంతర్దృష్టులు',
        'recommendations': 'సిఫార్సులు',
        'report_footer': 'కృషక్ ఎరువు సిఫార్సు వ్యవస్థ ద్వారా జనరేట్ చేయబడింది',
        'model_confidence_comparison': 'మోడల్ నమ్మకం పోలిక',
        'confidence': 'నమ్మకం',
        'models': 'మోడళ్లు',
        'report_contents': 'నివేదిక విషయాలు',
        'input_parameters_desc': 'వినియోగదారు ఇన్‌పుట్ డేటా',
        'predictions_desc': 'ML మోడల్ ఫలితాలు',
        'soil_health_desc': 'విశ్లేషణ మరియు సిఫార్సులు',
        'weather_data_desc': 'ప్రస్తుత వాతావరణ పరిస్థితులు',
        'summary_desc': 'ఈ అవలోకనం'
    }
}


def get_translation(key: str, language: str = 'en') -> str:
    """Get translation for a given key and language."""
    return TRANSLATIONS.get(language, TRANSLATIONS['en']).get(key, key)


def get_soil_type_recommendation(soil_type: str, language: str = 'en') -> str:
    """Get soil type specific recommendation in the specified language."""
    soil_type_key = f'soil_type_{soil_type.lower()}'
    return get_translation(soil_type_key, language)
